name: Reviewers Lottery
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  Review-lottery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'