name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
env:
  API_URL: 'API_URL'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - steps:
        - name: Print Variable
          run: echo "Hello $API_URL"