name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]

jobs:
  check_var:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret Variable
        run: echo ${{secrets.API_KEY}}