name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
    Review-lottery:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: uesteibar/reviewer-lottery@v2
            with:
                repo-token: '${{ secrets.GITHUB_TOKEN }}'